### ISSUE TITLE
Using Stealth to monitor multiple clients

### ISSUE THREAD

**Issue by mabushey** [fbb-git/stealth#1]
It appears Stealth requires something like "DEFINE TARGET hostname". Would it work to use a bash wrapper to use sed to change the hostname in the conf file, run the scan, and then repeat for about 30 clients?

**Comment by fbb-git** [comment]
Dear Michael Bushey, you wrote:

> It appears Stealth requires something like "DEFINE TARGET hostname". Would
> it work to use a bash wrapper to use sed to change the hostname in the conf
> file, run the scan, and then repeat for about 30 clients?

Hi Michael,

Thanks for your question about Stealth. 

The usual approach that's taken when Stealth is used is that there is a
separate config file for each host. But that's just how it's commonly done. In
the end the Stealth monitor runs a separate stealth process for each of its
clients, and each Stealth process writes its results to its own log-file, has
its own socket, etc.. Just changing the hostname therefore probably won't work
very well. But if your wrapper not only changes the hostname but also the
other host-specific details then it should work. Of course, unless you add
some delay between the 30 invocations your network interface card might not be
overly happy, and you will have a spike in the computer's load because
suddenly there are these 30 processes actively being run. But that's not
something that's specifically related to Stealth, I guess.

Cheers,

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by mabushey** [comment]
Frank,

First off thank you for your response. I'll create a conf file for each server to monitor. :)

This leaves two questions:
1. Is it recommended to run stealth by creating a bash script to call stealth for each server conf file `ie LIST=$(ls /root/stealth/*.pol)` , or it is possible to run something like `stealth /root/stealth/*pol`?
2.  One of the Debian examples `/usr/share/doc/stealth/examples/demo.pol.gz`,  appears wrong.
   When I run this code:

```
 43 LOCAL mkdir -p tmp                                               # local working directory
 44 LOCAL scp ${CLIENT}:/usr/bin/sha1sum     tmp                     # copy sha1sum to here
 45 LOCAL scp ${CLIENT}:/lib/x86_64-linux-gnu/libc.so.6      tmp     # and its libraries
 46 LOCAL scp ${CLIENT}:/lib64/ld-linux-x86-64.so.2 tmp      tmp
```

I get an output of:

```
# stealth /root/stealth/www1-test.pol 
timestamps use UTC
INTEGRITY_SCAN next.
LOCAL mkdir -p tmp
LOCAL scp root@www1:/usr/bin/sha1sum     tmp
LOCAL scp root@www1:/lib/x86_64-linux-gnu/libc.so.6      tmp
LOCAL scp root@www1:/lib64/ld-linux-x86-64.so.2 tmp      tmp
[Fatal] stealth terminated: non-zero exit value for
LOCAL mkdir -p tmp (EOC Thu Nov 12 19:16:42 2015 1)
```

```
# ls -l /root/stealth/www1/tmp/
total 1876
-rwxr-xr-x 1 root root  140928 Nov 12 19:16 ld-linux-x86-64.so.2
-rwxr-xr-x 1 root root 1729984 Nov 12 19:16 libc.so.6
-rwxr-xr-x 1 root root   43592 Nov 12 19:16 sha1sum
```

It successfully creates the tmp directory, then it scp's the files into it, then it fails on the directory creation it already did...

When I get this figured out I'll create a blog entry on setting up Stealth. While it seems there is relatively good in depth information, it seems that some of the basics are missing. Thanks again, I'm looking forward to having this working successfully. :)

**Comment by fbb-git** [comment]
Dear Michael Bushey, you wrote:

> Frank,
> 
> First off thank you for your response. I'll create a conf file for each
> server to monitor. :)

Thanks for your feedback and additional questions. I just read them, but it's
too late over here to give them the attention they deserve. I'll get back to
you (my) tomorrow.

Cheers,

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by fbb-git** [comment]
Dear Michael Bushey, you wrote:

> Frank,
> 
> First off thank you for your response. I'll create a conf file for each
> server to monitor. :)

So, as promised: below you find my answers to your questions. 

> This leaves two questions:
> 1. Is it recommended to run stealth by creating a bash script to call
> stealth for each server conf file `ie LIST=$(ls /root/stealth/*.pol)` , or
> it is possible to run something like `stealth /root/stealth/*pol`?

Not the latter (*pol). The bash script should work. Although, I normally run
stealth program(s) in the background, and have them inspect their client(s) at
random points in time. E.g., here's how I call stealth, together with its
configuration file (client's name is faked):

---

activation:

```
/usr/bin/stealth --daemon /root/stealth/client/small.uds -s \
    /root/stealth/client/skipfiles /root/stealth/client/small.pol
```

---

configuration:

# NOTE: `find' at this host doesn't support -perm /... yet;

# therefore, the deprecated -perm +... is used

#

#############################################

# this is the policy file for client

#############################################

USE BASE        /root/stealth/client/small
USE DIFF        /usr/bin/diff
USE EMAIL       root
USE MAILER      /root/bin/stealthmail
#USE MAILER      /usr/bin/mail
USE MAILARGS    -s "Client small STEALTH report" 
USE REPORT      report
USE SSH         /usr/bin/ssh -q root@client-fqdn \
                    -T -q exec /bin/bash --noprofile
USE SH          /bin/sh

########################################################

# Run remotely. Check all executables

# in the remote computer's bin directory

########################################################

LABEL \nexecutable files in /bin

CHECK LOG = remote/bin \
    /usr/bin/find /bin -xdev -perm +111  -type f -exec /usr/bin/sha1sum {} \;

########################################################

# Check all files that are s/guid root on the remote computer

########################################################

LABEL \nsuid/sgid/executable files uid or gid root on the / partition  
CHECK LOG = remote/root \
    /usr/bin/find / -xdev -type f -perm +6000 \
                    ( -user root -or -group root ) \
                    -exec /usr/bin/sha1sum {} \;

########################################################

# Check all files in the /etc directory

########################################################

LABEL \nfiles in /etc
CHECK LOG = remote/etc \
    /usr/bin/find /etc -type f -exec /usr/bin/sha1sum {} \;

################## part 2 #################################

%%

skip-files  /root/stealth/client/skipfiles
syslog
syslog-tag  CLIENT
verbosity   1
repeat      25m
random-interval 10m

################## end #################################

---

> 1.  One of the Debian examples `/usr/share/doc/stealth/examples/demo.pol.gz`,  appears wrong.
>    When I run this code:
> 
> ```
>  43 LOCAL mkdir -p tmp                                               # local working directory
>  44 LOCAL scp ${CLIENT}:/usr/bin/sha1sum     tmp                     # copy sha1sum to here
>  45 LOCAL scp ${CLIENT}:/lib/x86_64-linux-gnu/libc.so.6      tmp     # and its libraries
>  46 LOCAL scp ${CLIENT}:/lib64/ld-linux-x86-64.so.2 tmp      tmp
> ```
> 
> I get an output of:
> 
> ```
> # stealth /root/stealth/www1-test.pol 
> timestamps use UTC
> INTEGRITY_SCAN next.
> LOCAL mkdir -p tmp
> LOCAL scp root@www1:/usr/bin/sha1sum     tmp
> LOCAL scp root@www1:/lib/x86_64-linux-gnu/libc.so.6      tmp
> LOCAL scp root@www1:/lib64/ld-linux-x86-64.so.2 tmp      tmp
> [Fatal] stealth terminated: non-zero exit value for
> LOCAL mkdir -p tmp (EOC Thu Nov 12 19:16:42 2015 1)
> ```
> 
> ```
> # ls -l /root/stealth/www1/tmp/
> total 1876
> -rwxr-xr-x 1 root root  140928 Nov 12 19:16 ld-linux-x86-64.so.2
> -rwxr-xr-x 1 root root 1729984 Nov 12 19:16 libc.so.6
> -rwxr-xr-x 1 root root   43592 Nov 12 19:16 sha1sum
> ```
> 
> It successfully creates the tmp directory, then it scp's the files into it,
> then it fails on the directory creation it already did...

Interesting. The demo.pol.gz file indeed seems to need a bit of editing. I
changed the essential parts, and ran it with no errors. Here's the policy file
I used (again, I changed the actual TARGET name to 'client'):

---

################################################

# this is a demo policy file for stealth >= 1.01

################################################

# create several DEFINEs

```
# user on controller running stealth
DEFINE HOME     /home/frank

# host being scanned: TARGET
DEFINE TARGET   client

# A useful DEFINE for the find command.
DEFINE SETUID -xdev -type f -perm /u+s,g+s \( -user root -or -group root \)
```

# set up the non-default USE variables

```
# where will stealth store its results?
USE BASE        ${HOME}/${TARGET}

# who will get the overview of the results?
USE EMAIL       frank@localhost

# who will do the mailing ? (note that stealthmail doesn't mail, but 
#                           rather, writes /tmp/stealth.mail
USE MAILER      /usr/bin/mail

# what arguments will the mailer receive? 
USE MAILARGS    -s "${TARGET} demo STEALTH report"

# arguments used when executing a scp command reaching TARGET
# using a special ssh-key:
#DEFINE CLIENT   -i ${HOME}/.ssh/stealthkey root@${TARGET}
# using the standard ssh-key
DEFINE CLIENT   ${TARGET}

# how is ssh used to connect to the client?
USE SSH     /usr/bin/ssh -q client -T -q exec /bin/bash --noprofile
```

##############################################

# First, retrieve sha1sum and its libraries

# from the client, to be tested locally.

##############################################

LOCAL mkdir -p tmp                              # local working directory
LOCAL scp ${CLIENT}:/usr/bin/sha1sum     tmp     # copy sha1sum to here

# The remainder of the script was not used.

---

I used the following command to call stealth:

stealth --log demo.log --verbosity 3 demo.pol

which resulted in the following log entries:

---

Nov 13 10:12:27 loadSkipFiles: 0 lines
Nov 13 10:12:27 constructed the Integrity Scanner
Nov 13 10:12:27 max. download size: 10M
Nov 13 10:12:27 timestamps use UTC
Nov 13 10:12:27 Inserting EOC Fri Nov 13 09:12:27 2015 into /usr/bin/ssh -q client -T -q exec /bin/bash --noprofile
Nov 13 10:12:27 Waiting for EOC Fri Nov 13 09:12:27 2015 from /usr/bin/ssh -q client -T -q exec /bin/bash --noprofile
Nov 13 10:12:28 read line `EOC Fri Nov 13 09:12:27 2015'
Nov 13 10:12:28 GOT Sentinel
Nov 13 10:12:28 /usr/bin/ssh -q client -T -q exec /bin/bash --noprofile appears to be functioning well
Nov 13 10:12:28 INTEGRITY_SCAN next.
Nov 13 10:12:28 LOCAL mkdir -p tmp
Nov 13 10:12:28 nextCommand: inserting
Nov 13 10:12:28 mkdir -p tmp
Nov 13 10:12:28 and: echo EOC Fri Nov 13 09:12:28 2015 $?
Nov 13 10:12:28 read line`EOC Fri Nov 13 09:12:28 2015 0'
Nov 13 10:12:28 GOT Sentinel
Nov 13 10:12:28 LOCAL scp client-fqdn:/usr/bin/sha1sum     tmp
Nov 13 10:12:28 nextCommand: inserting
Nov 13 10:12:28 scp client-fqdn:/usr/bin/sha1sum     tmp
Nov 13 10:12:28 and: echo EOC Fri Nov 13 09:12:28 2015 $?
Nov 13 10:12:28 read line `EOC Fri Nov 13 09:12:28 2015 0'
Nov 13 10:12:28 GOT Sentinel
Nov 13 10:12:28 policy file processed
Nov 13 10:12:28 Integrity scan completed

## Nov 13 10:12:28 No new logs to mail

I also reran stealth on demo.pol (after removing all files
and directories previously created by stealth) keeping all its commands, and
that one also successfully completed. So, I don't really know why you had that
mkdir error message, but I noticed that I did have to change the #define SSH
line from

```
USE SSH         /usr/bin/ssh root@${TARGET} -q
```

to

```
USE SSH     /usr/bin/ssh -q root@{TARGET} -T -q exec /bin/bash --noprofile
```

(the root@ prefix should not be necessary if you're already logged in as
root). Maybe that helps?

> ... Thanks again, I'm looking forward to having this working
>   successfully. :)

Thanks for your questions. I hope my answers help you out. Personally, I
wouldn't worry too much about whether or not you get stealth successfully up
and running, as it's working fine on many different systems. In practice most
problems eventually are related to learning how to formulate the commands in
the policy files. Don't hesitate to ask if you have further questions.

Cheers,

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by mabushey** [comment]
Thank you for all your help Frank!

If I have this policy file with an intentional file not existing error on line 47:

```
 44 LOCAL mkdir -p tmp       # local working directory
 45 LOCAL scp ${CLIENT}:/usr/bin/sha1sum     tmp                  # copy sha1sum to here
 46 LOCAL scp ${CLIENT}:/lib/x86_64-linux-gnu/libc.so.6      tmp     # and its libraries
 47 LOCAL scp ${CLIENT}:/lib64/ld-linux-x86-64.so.2-bad  tmp
```

From the log:

```
13 Nov 13 20:45:48 mkdir -p tmp
 14 Nov 13 20:45:48 and: echo EOC Fri Nov 13 20:45:48 2015 $?
 15 Nov 13 20:45:48 read line `EOC Fri Nov 13 20:45:48 2015 0'
 16 Nov 13 20:45:48 GOT Sentinel
 17 Nov 13 20:45:48 LOCAL scp www1:/usr/bin/sha1sum     tmp
 18 Nov 13 20:45:48 nextCommand: inserting
 19 Nov 13 20:45:48 scp www1:/usr/bin/sha1sum     tmp
 20 Nov 13 20:45:48 and: echo EOC Fri Nov 13 20:45:48 2015 $?
 21 Nov 13 20:45:48 read line `EOC Fri Nov 13 20:45:48 2015 0'
 22 Nov 13 20:45:48 GOT Sentinel
 23 Nov 13 20:45:48 LOCAL scp www1:/lib/x86_64-linux-gnu/libc.so.6      tmp
 24 Nov 13 20:45:48 nextCommand: inserting
 25 Nov 13 20:45:48 scp www1:/lib/x86_64-linux-gnu/libc.so.6      tmp
 26 Nov 13 20:45:48 and: echo EOC Fri Nov 13 20:45:48 2015 $?
 27 Nov 13 20:45:48 read line `EOC Fri Nov 13 20:45:48 2015 0'
 28 Nov 13 20:45:48 GOT Sentinel
 29 Nov 13 20:45:48 LOCAL scp www1:/lib64/ld-linux-x86-64.so.2-bad  tmp
 30 Nov 13 20:45:48 nextCommand: inserting
 31 Nov 13 20:45:48 scp www1:/lib64/ld-linux-x86-64.so.2-bad  tmp
 32 Nov 13 20:45:48 and: echo EOC Fri Nov 13 20:45:48 2015 $?
 33 Nov 13 20:45:48 read line `EOC Fri Nov 13 20:45:48 2015 1'
 34 Nov 13 20:45:48 GOT Sentinel
 35 Nov 13 20:45:48 [Fatal] stealth terminated: non-zero exit value for
 36 Nov 13 20:45:48 LOCAL mkdir -p tmp (EOC Fri Nov 13 20:45:48 2015 1)
```

It looks like it is reporting the command from 3 back (Line 44 instead of 47) as the cause.

**Comment by mabushey** [comment]
From www1.pol: `55 LOCAL CHECK local/sha1sum /usr/bin/sha1sum tmp/*`

```
 36 Nov 13 21:52:38 LOCAL CHECK /root/stealth/www1/local/sha1sum /usr/bin/sha1sum tmp/*
 37 Nov 13 21:52:38 No `LOG =' specified in CHECK command `/root/stealth/www1/local/sha1sum /usr/bin/sha1sum tmp/*'
```

Looks like I should add `LOG =`: `55 LOCAL CHECK LOG = local/sha1sum /usr/bin/sha1sum tmp/*`

```
 36 Nov 13 21:54:35 LOCAL CHECK LOG = /root/stealth/w17/local/sha1sum /usr/bin/sha1sum tmp/*
 37 Nov 13 21:54:35 removed `LOG =', kept ` /root/stealth/w17/local/sha1sum /usr/bin/sha1sum tmp/*'
```

Nope, it's not happy either way. Seems like one should be correct and the other give a warning.

On page 16 of the PDF manual Stealth V.4.01.02, Under the LOCAL CHECK from `PathOffset is also optional...` to `...found
in command-to-be-executed.` is a section of words that to me appear random. I can make no meaning/purpose/function out of it. Is it trying to match binary data in the file being checked?

For some reason I need  `/usr/bin/sha1sum` to exist in the middle of that `LOCAL CHECK`. If I supply a random file it doesn't work. I don't understand why or what that is for. Is `/usr/bin/sha1sum` a path offset or part of the command?  If it's part of the command I would think it should be `"/usr/bin/sha1sum tmp/*"` in quotes so the parser [or silly human?] knows how to process it. It's a given that you know a lot more about parsers than I do... Logically I would think that CHECK would already imply a checksum exe. I just don't get it.

Thanks again for your help Frank, I appreciate your time in helping me out. :) I'm looking forward to coming up with a quick start guide to help people implement Stealth.

**Comment by mabushey** [comment]
Looking at some other examples where CHECK is calling `/usr/bin/find` I see that it's executing the binary, so the `/usr/bin/sha1sum` from my above post makes sense. Should PathOffset be removed from the documentation?

**Comment by mabushey** [comment]
Looks like I have things mostly working... Thanks again for your help. What do you recommend for the procedure when servers are updated? Delete the /root/stealth/www1 directory on the stealth server, do the `apt-get dist-upgrade` on the client, and then run stealth on the stealth server to recreate the permissions and sha1 logs?

**Comment by mabushey** [comment]
In the demo.pol example, we have this:

```
 63 CHECK remote/print.root \
 64     /usr/bin/find / -xdev -perm /6111 \( -user root -or -group root \) \
 65         -type f -printf "%m %n %s %p\n"
 66 CHECK remote/sha1.root \
 67     /usr/bin/find / -xdev -perm /6111  \( -user root -or -group root \) \
 68         -type f -exec /usr/bin/sha1sum {} \;
```

Besides throwing the options in ${SETUID}, wouldn't this do the same thing but cleaner?:

```
/usr/bin/find /etc -xdev -perm /6111 \( -user root -or -group root \) -type f -printf "%m %n %s " -exec /usr/bin/sha1sum {} \;
```

**Comment by fbb-git** [comment]
Dear Michael Bushey, you wrote:

> On page 16 of the PDF manual Stealth V.4.01.02, Under the LOCAL CHECK from `PathOffset is also optional...` to `...found
> in command-to-be-executed.` is a section of words that to me appear
> random. I can make no meaning/purpose/function out of it. Is it trying to
> match binary data in the exe?

Hm, I'll check this out. Sometimes I'm editing something without properly
removing old mush. Shit happens, and thanks for pointing to unclear sections.

> For some reason I need  `/usr/bin/sha1sum` to exist in the middle of that
> `LOCAL CHECK`. If I supply a random file it doesn't work. I don't understand
> why or what that is for. Is `/usr/bin/sha1sum` a path offset of part of the
> command?  

The sha1sum program is the program you want to use to check the file that's
locally available. The man-page gives a comparable example:

LOCAL CHECK LOG = local/sha256sum sha256sum /tmp/sha256sum
      This  command  checks  the SHA256 sum of the /tmp/sha256sum pro-
      gram. The resulting output is saved at BASE/local/sha256sum. The
      program  must  succeed  (i.e.,  sha256sum  must  return  a  zero
      exit-value).

So, the plain sha256sum refers to the program that's locally run, and it
receives as its argument the file /tmp/sha256sum, which was retrieved from the
client just before the LOCAL CHECK LOG command. 

If it's part of the command I would think it should be

> `"/usr/bin/sha1sum tmp/*"` in quotes so the parser [or silly human?] knows
> how to process it. It's a given that you know a lot more about parsers than
> I do... Logically I would think that CHECK would already imply a checksum
> exe. I just don't get it.

Well, CHECK simply means that the output of the current command should be
identical to a reviously collected output. So in this case, a previously
obtained output of 
        sha256sum /tmp/sha256sum
must be identical to the output obtained with the currently executed
        sha256sum /tmp/sha256sum
program.

> Thanks again for your help Frank, I appreciate your time in helping me
> out. :) I'm looking forward to coming up with a quick start guide to help
> people implement Stealth.

Nice! Me too! :-)

(next I check and if necessary reply to your additional postings)

Cheers,

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by fbb-git** [comment]
Dear Michael Bushey, you wrote:

> Looking at some other examples where CHECK is calling `/usr/bin/find` I see
> that it's executing the binary, so the `/usr/bin/sha1sum` from my above post
> makes sense. Should PathOffset be removed from the documentation?

Maybe: something else for me to check :-)

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by fbb-git** [comment]
Dear Michael Bushey, you wrote:

> Looks like I have things mostly working... Thanks again for your help. What
> do you recommend for the procedure when servers are updated? Delete the
> /root/stealth/www1 directory on the stealth server, do the `apt-get
> dist-upgrade` on the client, and then run stealth on the stealth server to
> recreate the permissions and sha1 logs?

That's one possibility. I usually, after an update of the client computers,
expect lots of changes, and briefly browse Stealth's report to see if there's
something remarkable there that needs further investigation. But in my
experience that's seldom necessary.

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by fbb-git** [comment]
Dear Michael Bushey, you wrote:

> In the demo.pol example, we have this:
> 
> ```
>  63 CHECK remote/print.root \
>  64     /usr/bin/find / -xdev -perm /6111 \( -user root -or -group root \) \
>  65         -type f -printf "%m %n %s %p\n"
>  66 CHECK remote/sha1.root \
>  67     /usr/bin/find / -xdev -perm /6111  \( -user root -or -group root \) \
>  68         -type f -exec /usr/bin/sha1sum {} \;
> ```
> 
> Besides throwing the options in ${SETUID}, wouldn't this do the same thing but cleaner?:
> 
> ```
> /usr/bin/find /etc -xdev -perm /6111 \( -user root -or -group root \) -type
> f -printf "%m %n %s " -exec /usr/bin/sha1sum {} \;
> ```

That's (in all humbleness) the beauty of Stealth: you can do whatever you
want. In the example I wanted logs of both the printf output and the sha1sum
output. But that's just to illustrate some of the possibilities. Of course, if
you (or whoever uses Stealth) wants to use other programs, or other
invocations. that's absolutely OK

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by mabushey** [comment]
Here's what I'm using to launch stealth (cron calls this script):

```
#!/bin/bash

CONFS=$(ls /root/stealth/conf/ | sort -R)
for CONF in $CONFS; do
  /bin/sleep $(( ( RANDOM % 600 )  + 1 )) ## Wait up to 10min
  /usr/bin/stealth /root/stealth/conf/${CONF}
done
```

Thanks for all your help Frank! I'm planning on doing a how to write-up for stealth in about 2 weeks.
